<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libreria [
    <!ELEMENT libreria (libro+)>
    <!ELEMENT libro (titulo, autor, anio_publicacion, editorial)>
    <!ELEMENT titulo (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT anio_publicacion (#PCDATA)>
    <!ELEMENT editorial (#PCDATA)>
]>
<libreria>
    <libro>
        <titulo>Don Quijote de la Mancha</titulo>
        <autor>Miguel de Cervantes</autor>
        <anio_publicacion>1605</anio_publicacion>
        <editorial>Imprenta de Francisco de Robles</editorial>
    </libro>
    <libro>
        <titulo>Cien años de soledad</titulo>
        <autor>Gabriel García Márquez</autor>
        <anio_publicacion>1967</anio_publicacion>
        <editorial>Círculo de Lectores</editorial>
    </libro>
</libreria>
