=== erikmozos/LMSGI/XML_TEMA3/Exercicis_Estudi/empresa.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="empresa">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleado" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string" />
                            <xs:element name="edad" type="xs:string" />
                            <xs:element name="puesto" type="xs:string" />
                            <xs:element name="salario" type="xs:string" />
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== erikmozos/LMSGI/XML_TEMA3/Exercicis_Estudi/empresa.xml
<?xml version="1.0" encoding="UTF-8"?>
<empresa xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
xs:noNamespaceSchemaLocation="empresa.xsd">
    <empleado id="1">
        <nombre>Juan Perez</nombre>
        <edad>30</edad>
        <puesto>Desarrollador</puesto>
        <salario>50000</salario>
    </empleado>
    
    <empleado id="2">
        <nombre>Maria Rodriguez</nombre>
        <edad>25</edad>
        <puesto>Dise√±ador</puesto>
        <salario>45000</salario>
    </empleado>
    
    <empleado id="3">
        <nombre>Carlos Gomez</nombre>
        <edad>35</edad>
        <puesto>Gerente de Proyecto</puesto>
        <salario>60000</salario>
    </empleado>
</empresa>
