=== erikmozos/LMSGI/XML_TEMA3/Exercicis_Estudi/estudiantes.dtd
<!ELEMENT estudiantes (estudiante+)>
<!ELEMENT estudiante (nombre,edad,curso)>
<!ATTLIST estudiante id NMTOKEN #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT curso (#PCDATA)>

=== erikmozos/LMSGI/XML_TEMA3/Exercicis_Estudi/estudiantes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE estudiantes SYSTEM "estudiantes.dtd">
<estudiantes>
    <estudiante id="1">
        <nombre>María García</nombre>
        <edad>22</edad>
        <curso>Informática</curso>
    </estudiante>
    <estudiante id="2">
        <nombre>Juan Rodríguez</nombre>
        <edad>20</edad>
        <curso>Matemáticas</curso>
    </estudiante>
</estudiantes>
