=== erikmozos/LMSGI/XML_TEMA3/Erik_Mozos_Moll_XML/examenXML_Erik_Mozos/lmgsi_examen_ud3/ex7.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="granja">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="lloc" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="productor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="xs:string">
                                            <xs:attribute name="id" type="xs:string" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="animales">
                                <xs:complexType>
                                    <xs:choice maxOccurs="unbounded">

                                            <xs:sequence>
                                                <xs:element name="perro" type="decompa"/>
                                                <xs:element name="cerdo" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                    <xs:attribute name="cantidad" type="xs:integer" />
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>

                                            <xs:sequence>
                                                <xs:element name="gato" type="decompa" maxOccurs="2"/>
                                                <xs:element name="cerdo" maxOccurs="unbounded">
                                                    <xs:complexType>
                                                    <xs:attribute name="cantidad" type="xs:integer" />
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>

                                    </xs:choice>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="decompa">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="decompania" type="xs:boolean" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== erikmozos/LMSGI/XML_TEMA3/Erik_Mozos_Moll_XML/examenXML_Erik_Mozos/lmgsi_examen_ud3/ejercicio7.xml
<?xml version="1.0" encoding="UTF-8"?>
<granja xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
  xs:noNamespaceSchemaLocation="ex7.xsd">
  <!--Todos los atributos son obligatorios menos cantidad. 
    Si la etiqueta <cerdo> tiene un atributo solo podrá haber una-->
  <lloc>
    <!--Mínimo una etiqueta productor-->
    <productor id="prod1">Productor1</productor>
    <productor id="prod2">Productor2</productor>
    <animales> <!--Solo puede haber una etiqueta <animales>-->
      <gato decompania="true">Un gato</gato> <!--Puede haber 1 o 2 gatos o 1 perro pero no ambos-->
      <gato decompania="true">Otro gato</gato>
      <!--O hay una sola etiqueta cerdo con atributo o hay varias etiquetas vacías sin atributo-->
      <cerdo cantidad="5"/>      
    </animales>    
  </lloc>  
  <lloc>
    <productor id="prod3">Productor3</productor>
    <animales>
      <perro decompania="true">Un perro</perro>
      <cerdo/>
      <cerdo/>     
    </animales>  
  </lloc> 
</granja>
